CREATE SCHEMA IF NOT EXISTS AP;

CREATE TABLE IF NOT EXISTS AP.AIRLINES(
airline_id SERIAL PRIMARY KEY,
airline_code VARCHAR(50) UNIQUE NOT NULL,
airline_name VARCHAR(100) NOT NULL, 
owned_by VARCHAR(100), -- REFERENCED COLUMN
IS_ACTIVE BOOL DEFAULT '1',
created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AP.FLIGHT_DETAILS(
FLIGHT_NUMBER SERIAL PRIMARY KEY,
flight_name VARCHAR(100) NOT NULL,
flight_code VARCHAR(50) UNIQUE NOT NULL,
airline_id SERIAL REFERENCES AP.AIRLINES(airline_id) ON DELETE SET NULL,
IS_ACTIVE BOOL DEFAULT '1',
created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AP.FLIGHT_SCHEDULE(
schedule_id SERIAL PRIMARY KEY,
flight_number SERIAL REFERENCES AP.FLIGHT_DETAILS( FLIGHT_NUMBER) ON DELETE CASCADE,
arrival_Port VARCHAR(100) NOT NULL, --REFERENCED COLUMN 
departure_port VARCHAR(100) NOT NULL,
arrival_ts TIMESTAMP,
departure_ts TIMESTAMP,
created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);